### ISSUE TITLE
How to ignore org-mode syntax?

### ISSUE THREAD

**Issue by johannes-wolf** [emacs-languagetool/lsp-ltex#10]
Thank you for lsp-ltex!
I've got one question: how to make lsp-ltex org-mode aware? Regarding the documentation of the ltex server, org-mode should work out of the box, but for me it does not. lsp-ltex marks org-mode tags (e.g., “#+OPTIONS: …”) as spelling error.

**Comment by jcs090218** [comment]
I think this is an upstream issue. Maybe there is misparsing going on from the language server.

Can you try reporting this issue to [ltex-ls](https://github.com/valentjn/ltex-ls)?

**Comment by johannes-wolf** [comment]
Fixed it by adding 
```
(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(org-mode . "org")))
```
to my emacs (doom) init file.

**Comment by valentjn** [comment]
Confirming this is not an upstream issue.

**Comment by jcs090218** [comment]
@valentjn Thanks for the confirmation!

@yyoncho Do we need to change the variable `lsp-language-id-configuration` in order to make the corresponding language server work in `org-mode`? Is it required?

Another related issue is [lsp-grammarly/#23](https://github.com/emacs-grammarly/lsp-grammarly/issues/23).

**Comment by jcs090218** [comment]
Should fix in the upstream, see https://github.com/emacs-lsp/lsp-mode/pull/3235.

Thanks for reporting this issue to us!
